### ISSUE TITLE
SIGSEGV in bufferpool

### ISSUE THREAD

**Issue by DylanSale** [aws/amazon-cloudwatch-logs-for-fluent-bit#134]
When running the cloudwatch output plugin with fluent bit 1.6.8. It is getting stuck in a crash loop.

This is on a raspberry pi 3 running raspbian. I compiled the cloudwatch plugin from source 1.6.0 tag using go 1.12.

The system logs show this stack trace:
```
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: Fluent Bit v1.6.8
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: * Copyright (C) 2019-2020 The Fluent Bit Authors
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: * Copyright (C) 2015-2018 Treasure Data
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: * https://fluentbit.io
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info] Configuration:
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  flush time     | 5.000000 seconds
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  grace          | 5 seconds
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  daemon         | 0
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info] ___________
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  inputs:
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      systemd
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info] ___________
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  filters:
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      rewrite_tag.0
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      record_modifier.1
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      record_modifier.2
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      modify.3
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info] ___________
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  outputs:
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]      cloudwatch.0
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info] ___________
Dec 11 09:57:47 logr-edge-7 td-agent-bit[15876]: [2020/12/11 09:57:47] [ info]  collectors:

.... 

Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x751c86d0]
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: goroutine 17 [running, locked to thread]:
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: runtime/internal/atomic.goLoad64(0x4468410c, 0x0, 0x0)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:127 +0x1c
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: github.com/valyala/bytebufferpool.(*Pool).Get(0x44684064, 0x33)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         /home/enabled/.go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/pool.go:54 +0x5c
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch.(*OutputPlugin).setGroupStreamNames(0x44684000, 0x445f6630)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         /home/enabled/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch/cloudwatch.go:503 +0x84
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch.(*OutputPlugin).AddEvent(0x44684000, 0x445f6630, 0x75b85c68)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         /home/enabled/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch/cloudwatch.go:356 +0x238
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: main.FLBPluginFlushCtx(0x6449c090, 0x6440c052, 0x1cf, 0x6446b340, 0x75224d50)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         /home/enabled/amazon-cloudwatch-logs-for-fluent-bit/fluent-bit-cloudwatch.go:191 +0x2b8
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]: main._cgoexpwrap_19a10b653c9e_FLBPluginFlushCtx(0x6449c090, 0x6440c052, 0x1cf, 0x6446b340, 0x0)
Dec 11 09:57:52 logr-edge-7 td-agent-bit[15876]:         _cgo_gotypes.go:86 +0x34
Dec 11 09:57:52 logr-edge-7 systemd[1]: td-agent-bit.service: Main process exited, code=killed, status=6/ABRT
Dec 11 09:57:52 logr-edge-7 systemd[1]: td-agent-bit.service: Unit entered failed state.
Dec 11 09:57:52 logr-edge-7 systemd[1]: td-agent-bit.service: Failed with result 'signal'.
```

Any help as to what could be causing the segfault would be greatly appreciated.

**Comment by zhonghui12** [comment]
Hi @DylanSale,

Can you please try go 1.13 or higher? We use go 1.13 for current code and some part of the code may need a higher version than 1.12. 

Also, we built a core CloudWatch plugin in C: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch. You can also consider to use this one, it will work if you can compile and run Fluent Bit on raspberry pi.

 Thanks.

**Comment by DylanSale** [comment]
Hi @zhonghui12, thanks for your suggestions. I tried compiling with go 1.13.15 but it got the same error. This also happens when running on fluent bit 1.5.7. 

I also gave the c plugin a go but unfortunately I am using the `credential_process` credentials type in my aws profile file which doesn't seem to be supported by it. (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html)

**Comment by DylanSale** [comment]
I managed to get the c plugin working. 

For what it is worth I did find that some of the log messages were missing the `log_key` field specified in the config, which might have been the cause of the crash I was experiencing (the c plugin seems to just warn about entries missing this field, but skips them).

This was my config:
```
[OUTPUT]
    Name             cloudwatch
    Match            docker.*
    region           ap-southeast-2
    log_group_name   xxx
    log_stream_prefix xxx-
    auto_create_group false
    log_key          log
    Retry_Limit      False

    #Only keep up to 1Gb of logs if offline to stop the system from dying
    storage.total_limit_size  1024M
```

For now I have moved to the native fluent bit plugin however.

**Comment by zhonghui12** [comment]
Close this one as C plugin works fine and no more discussion since this year.
